spring:
  kafka:
    bootstrap-servers: ${MSK_BROKERS}

  cassandra:
    keyspace-name: ad_insights
    contact-points: ${CASSANDRA_HOST}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      ssl: true

resilience4j:
  circuitbreaker:
    instances:
      adService:
        failureRateThreshold: 50
  bulkhead:
    instances:
      redisBulkhead:
        maxConcurrentCalls: 50

      cassandraBulkhead:
        maxConcurrentCalls: 30

  thread-pool-bulkhead:
    instances:
      redisBulkhead:
        maxThreadPoolSize: 20
        coreThreadPoolSize: 10

      cassandraBulkhead:
        maxThreadPoolSize: 20

logging:
  level:
    root: INFO